version: "3"

volumes:
  db-volume:

services:

  api:
    build: .
    environment:
      PORT: 8000
      DB_HOST: db
      DB_NAME: tarpaulin-db
      DB_USER: tarpaulin
      DB_PASS: tarpaulin
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8000:8000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tarpaulin-db
      MYSQL_USER: tarpaulin
      MYSQL_PASSWORD: tarpaulin
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - 6379:6379
